version: '3.9'

networks:
  nginx-php82-postgres-rabbit-redis:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82
      - postgres
    networks:
      - nginx-php82-postgres-rabbit-redis

  php82:
    build:
      context: .
      dockerfile: ./etc/docker/php-fpm/Dockerfile
    container_name: php82-container
    ports:
      - "9002:9000"
    volumes:
      - .:/var/www
    networks:
      - nginx-php82-postgres-rabbit-redis

  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_app
    ports:
      - "5432:5432"

  redis:
    image: redis:5-alpine
    container_name: redis-container
    networks:
      - nginx-php82-postgres-rabbit-redis

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit-container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nginx-php82-postgres-rabbit-redis

volumes:
  db-data: