version: '3.8'

services:

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_app
    ports:
      - "15432:5432"
    expose:
      - 5432
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82
    networks:
      - internal

  php82:
    build:
      context: .
      dockerfile: ./etc/docker/php-fpm/Dockerfile
    container_name: php82-container
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "9002:9000"
    volumes:
      - .:/var/www
    depends_on:
      - database
    networks:
      - internal

  redis:
    image: redis:5-alpine
    container_name: redis-container
#    networks:
#      - nginx-php82-postgres-rabbit-redis

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit-container
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  internal:
